### ISSUE TITLE
segfault with JSON-post that contains dollar-sign

### ISSUE THREAD

**Issue by grindhold** [JoeDog/siege#104]
got siege to segfault with the following entry in my siege url-file:
```
https://some.url.org POST {"url":"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/1cYAAOSwT6pVlQA-/$/$_57.JPG", "tho    roughness":1}
```
bt looks like this:
```
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff6d36076 in __GI_getenv (name=name@entry=0x0) at getenv.c:35
#2  0x00005555555633a0 in evaluate (hash=hash@entry=0x55555577e350, 
    buf=0x5555557a66d0 "https://some.url.de POST {\"url\":\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/1cYAAOSwT6pVlQA-/$/$_57.JPG\", \"thoroughness\":1}", buf@entry=0x55555577e380 "X\233\t\367\377\177") at eval.c:70
#3  0x000055555556181b in read_cfg_file (l=0x55555577e330, filename=<optimized out>) at cfg.c:144
#4  0x000055555555adb7 in __urls_setup () at main.c:370
#5  main (argc=3, argv=0x7fffffffe158) at main.c:398
```

in general, json works, i tested it a lot.
it works if i remove the dollar-signs from the string.

tested with git-master on debian linux

**Comment by petrpokorny-home24** [comment]
I got the same issue with URLs that contain dollar-sign in general (no JSON).
It works after I removed all URLs that contained dollar-sign.
