### ISSUE TITLE
Segmentation fault on Alpine linux Docker

### ISSUE THREAD

**Issue by tinnightcap** [JoeDog/siege#124]
I compiled on Alpine linux in Docker and the when executing am getting a segfault. I had to make a few changes to get through the compilation which I will outline in case that might be part of the problem.

I got this error during make:
```
hash.c:57:9: error: unknown type name 'u_int32_t'
```
Which I managed to get around by:
```
sed -i[.bak] 's/u_int32_t/uint32_t/g' src/hash.c
sed -i[.bak2] 's/#include <stdio.h>/#include <stdint.h>\n&/' src/hash.c
```
Basically renaming the int and including stdint.h above stdio.h

I then got this error:
```
page.c:13:8: error: expected identifier or '(' before numeric constant
```

Which I got around by:
```
sed -i[.bak] 's/PAGESIZE/MEMPAGESIZE/g' src/page.c
```
Found that PAGESIZE might be some sort of builtin (google and a bit of a guess here)

After that siege compiled and installed just fine, I can get configuration (verified with -C) and help, etc to function. Trouble is when I attempt to run it I get a segfault.

```
(gdb) run -c 1 https://pto.allizom.org
Starting program: /usr/local/bin/siege -c 1 https://pto.allizom.org
[New LWP 19]
[New LWP 20]
** SIEGE 4.0.4
** Preparing 1 concurrent users for battle.
The server is now under siege...

Thread 2 "siege" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 19]
0x00007ffff7dc22f5 in memset () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7dc22f5 in memset () from /lib/ld-musl-x86_64.so.1
#1  0x0000555555560a78 in memset (__n=81920, __c=0, __d=0x7ffff7fdcf60) at /usr/include/fortify/string.h:70
#2  cookies_header (this=0x7ffff7d71d60, host=0x7ffff7b08e20 "pto.allizom.org", newton=newton@entry=0x7ffff7ff1850 "") at cookies.c:183
#3  0x0000555555564fbf in http_get (C=0x5555557ad300, U=U@entry=0x5555557acdc0) at http.c:165
#4  0x000055555555dd57 in __http (U=0x5555557acdc0, this=0x5555557acfe0) at browser.c:480
#5  __request (this=this@entry=0x5555557acfe0, U=U@entry=0x5555557acdc0) at browser.c:406
#6  0x000055555555ee24 in start (this=0x5555557acfe0) at browser.c:295
#7  0x0000555555561d9f in crew_thread (crew=0x5555557ad120) at crew.c:141
#8  0x00007ffff7dc3b57 in ?? () from /lib/ld-musl-x86_64.so.1
#9  0x0000000000000000 in ?? ()
```

The URL I attempt to hit makes no difference, and there is no difference if it is http or https. I did not see any errors in ./configure or the make output, am happy to provide them if that would help.

**Comment by scardracs** [comment]
Using musl also fails on gentoo https://bugs.gentoo.org/719686. As noticed on comment 8 using u_int32_t is not POSIX-compatible
