### ISSUE TITLE
[HELP] Siege with 'Lifting the server siege...' Error

### ISSUE THREAD

**Issue by stkeke** [JoeDog/siege#225]
I probably have not provided enough data for you to do troubleshooting, if you need any more information, please advise, I can reproduce and collect.

# Description
We are using latest `siege` to benchmark our Nginx/Wordpress/Mariadb container group on Ubuntu 22.04 Linux with 132 threads.
We frequently came across 'Lifting the server siege...' error with command 
`/usr/local/bin/siege -c200 -t90S -i -b -f/tmp/siege-script-urls-list-1690350042.txt`
I just wondered if we gave too big `-c` option with 200?

# Siege Debug Build
```bash
ARG SIEGE_REPO=https://github.com/JoeDog/siege.git
CFLAGS='-g -O0' 
git clone ${SIEGE_REPO} && \
    cd siege && \
    sed -i "s|limit = 255|limit = 1024|" ./doc/siegerc.in && \
    sed -i "s|parser = true|parser = false|" ./doc/siegerc.in && \
    sed -i "s|verbose = true|verbose = false|" ./doc/siegerc.in && \
    sed -i "s|logging = true|logging = false|" ./doc/siegerc.in && \
    utils/bootstrap && \
    ./configure --with-ssl=/usr/bin/openssl && \
    make -j && \
    make install
```

# Siege Version
[root@a864832e0b79 siege]# siege -v
SIEGE 4.1.7-b5

# GDB breakpoint and backtrace.
I compiled siege with debug options and here is my gdb screen snapshot.

```bash
# gdb output with error --- thread 202 hit breakpoint at handler.c:74
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/local/bin/siege -c200 -t90S -i -b -f/tmp/siege-script-urls-list-1690350042.txt
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, main (argc=6, argv=0x7ffe789c4648) at main.c:391
391       void  *   status   = NULL;
(gdb) c
Continuing.
[New Thread 0x7f0596e20700 (LWP 15218)]
...
[New Thread 0x7f0532557700 (LWP 15419)]
** SIEGE 4.1.7-b5
** Preparing 200 concurrent users for battle.
The server is now under siege...[Thread 0x7f0532557700 (LWP 15419) exited]
[Switching to Thread 0x7f0532d58700 (LWP 15418)]

Thread 202 "siege" hit Breakpoint 3, sig_handler (crew=0xbe0640) at handler.c:74
74          fprintf(stderr, "\nLifting the server siege...");

(gdb) bt
#0  sig_handler (crew=0xbe0640) at handler.c:74
#1  0x00007f0597d881ca in start_thread () from /lib64/libpthread.so.0
#2  0x00007f0596e5ae73 in clone () from /lib64/libc.so.6
(gdb) p *crew
$1 = {size = 200, maxsize = 200, cursize = 0, total = 200, head = 0x0, tail = 0x0, block = boolean_false, closed = boolean_true, 
  shutdown = boolean_true, threads = 0xbea2d0, lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, 
      __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, not_empty = {__data = {{
        __wseq = 2583, __wseq32 = {__low = 2583, __high = 0}}, {__g1_start = 2575, __g1_start32 = {__low = 2575, __high = 0}}, __g_refs = {0, 0}, 
      __g_size = {0, 0}, __g1_orig_size = 16, __wrefs = 0, __g_signals = {0, 0}}, 
    __size = "\027\n\000\000\000\000\000\000\017\n", '\000' <repeats 22 times>, "\020", '\000' <repeats 14 times>, __align = 2583}, not_full = {
    __data = {{__wseq = 0, __wseq32 = {__low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, 
      __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, __size = '\000' <repeats 47 times>, __align = 0}, empty = {
    __data = {{__wseq = 3, __wseq32 = {__low = 3, __high = 0}}, {__g1_start = 1, __g1_start32 = {__low = 1, __high = 0}}, __g_refs = {0, 0}, 
      __g_size = {0, 0}, __g1_orig_size = 4, __wrefs = 0, __g_signals = {0, 0}}, 
    __size = "\003\000\000\000\000\000\000\000\001", '\000' <repeats 23 times>, "\004", '\000' <repeats 14 times>, __align = 3}}
(gdb) thread apply all where

Thread 202 (Thread 0x7f0532d58700 (LWP 15418)):
#0  sig_handler (crew=0xbe0640) at handler.c:74
#1  0x00007f0597d881ca in start_thread () from /lib64/libpthread.so.0
#2  0x00007f0596e5ae73 in clone () from /lib64/libc.so.6

Thread 201 (Thread 0x7f0533559700 (LWP 15417)):
#0  0x00007f0597d91ab4 in read () from /lib64/libpthread.so.0
#1  0x0000000000416d59 in socket_read (C=C@entry=0x7f04d0000b60, vbuf=vbuf@entry=0x7f0533556c7f, len=len@entry=1) at sock.c:626
#2  0x000000000040f2b9 in http_read_headers (C=0x7f04d0000b60, U=U@entry=0xb9d760) at http.c:444
#3  0x0000000000407373 in __http (U=0xb9d760, this=0xbcc530) at browser.c:501
#4  __request (this=this@entry=0xbcc530, U=U@entry=0xb9d760) at browser.c:414
#5  0x00000000004085cd in start (this=0xbcc530) at browser.c:296
#6  0x000000000040b215 in crew_thread (crew=0xbe0640) at crew.c:141
#7  0x00007f0597d881ca in start_thread () from /lib64/libpthread.so.0
#8  0x00007f0596e5ae73 in clone () from /lib64/libc.so.6

Thread 200 (Thread 0x7f0533d5a700 (LWP 15416)):
#0  0x00007f0597d91ab4 in read () from /lib64/libpthread.so.0
#1  0x0000000000416d59 in socket_read (C=C@entry=0x7f03c4000b60, vbuf=vbuf@entry=0x7f0533d57c7f, len=len@entry=1) at sock.c:626
#2  0x000000000040f2b9 in http_read_headers (C=0x7f03c4000b60, U=U@entry=0xbaf410) at http.c:444
#3  0x0000000000407373 in __http (U=0xbaf410, this=0xbcb2a0) at browser.c:501
#4  __request (this=this@entry=0xbcb2a0, U=U@entry=0xbaf410) at browser.c:414
#5  0x00000000004085cd in start (this=0xbcb2a0) at browser.c:296
#6  0x000000000040b215 in crew_thread (crew=0xbe0640) at crew.c:141
#7  0x00007f0597d881ca in start_thread () from /lib64/libpthread.so.0
#8  0x00007f0596e5ae73 in clone () from /lib64/libc.so.6

Thread 199 (Thread 0x7f053455b700 (LWP 15415)):
#0  0x00007f0597d91ab4 in read () from /lib64/libpthread.so.0
#1  0x0000000000416d59 in socket_read (C=C@entry=0x7f0498000b60, vbuf=vbuf@entry=0x7f0534558c7f, len=len@entry=1) at sock.c:626
#2  0x000000000040f2b9 in http_read_headers (C=0x7f0498000b60, U=U@entry=0xb964c0) at http.c:444
#3  0x0000000000407373 in __http (U=0xb964c0, this=0xbcdab0) at browser.c:501
#4  __request (this=this@entry=0xbcdab0, U=U@entry=0xb964c0) at browser.c:414
#5  0x00000000004085cd in start (this=0xbcdab0) at browser.c:296
#6  0x000000000040b215 in crew_thread (crew=0xbe0640) at crew.c:141
#7  0x00007f0597d881ca in start_thread () from /lib64/libpthread.so.0
#8  0x00007f0596e5ae73 in clone () from /lib64/libc.so.6

Thread 198 (Thread 0x7f0534d5c700 (LWP 15414)):
#0  0x00007f0597d91ab4 in read () from /lib64/libpthread.so.0
#1  0x0000000000416d59 in socket_read (C=C@entry=0x7f0494000b60, vbuf=vbuf@entry=0x7f0534d59c7f, len=len@entry=1) at sock.c:626
#2  0x000000000040f2b9 in http_read_headers (C=0x7f0494000b60, U=U@entry=0xb939a0) at http.c:444
```

**Comment by stkeke** [comment]
This issue is similar to https://github.com/JoeDog/siege/issues/4 and fixed by https://sourceware.org/pipermail/libc-alpha/2023-April/147654.html

**Comment by stkeke** [comment]
Close this issue.
